#!/usr/bin/env python3
"""Generate (and verify) the store-mutator call-site manifest for specs/0002.

The audit's first two enumerations were both incomplete — one from memory, one
from a grep that keyed on assignment. This derives the list from the mutator
INTERFACE and the call sites that reach it, so the artifact is reproducible
rather than asserted. `--check` fails when the code and the manifest disagree,
which is what stops the manifest becoming another prose claim.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "veracium"
BASE = SRC / "store" / "base.py"
MANIFEST = ROOT / "specs" / "generated" / "0002-audit-manifest.md"

# a mutator is a Store method that writes persistent state
MUTATOR_DEF = re.compile(r"^\s*def (add_\w+|invalidate_\w+|delete_\w+|forget_\w+|set_\w+)\(", re.M)


def mutators() -> list[str]:
    return sorted(set(MUTATOR_DEF.findall(BASE.read_text())))


DEF = re.compile(r"^(\s*)def (\w+)\(")


def call_sites(names: list[str]) -> list[tuple[str, str, str, int, int]]:
    """(path, enclosing def, mutator, line) for every call outside the store impls.

    Keyed on the ENCLOSING FUNCTION, not the line number, so a disposition
    survives unrelated edits above it. Line numbers are informational only —
    they are not part of the identity and never cause a --check failure.
    """
    out = []
    rx = re.compile("|".join(rf"\.{n}\(" for n in names))
    for p in sorted(SRC.rglob("*.py")):
        rel = p.relative_to(ROOT).as_posix()
        if "/store/" in rel:          # the implementations themselves, not call sites
            continue
        stack = []
        for i, line in enumerate(p.read_text().splitlines(), 1):
            d = DEF.match(line)
            if d:
                indent = len(d.group(1))
                while stack and stack[-1][0] >= indent:
                    stack.pop()
                stack.append((indent, d.group(2)))
            m = rx.search(line)
            if m and not line.lstrip().startswith("#"):
                where = ".".join(n for _, n in stack) or "<module>"
                mut = m.group(0).strip(".(")
                # several sites share (file, def, mutator) — e.g. apply_supersession
                # calls add_edge three times — so identity carries an ordinal.
                nth = 1 + sum(1 for r, w, mm, _, _ in out
                              if (r, w, mm) == (rel, where, mut))
                out.append((rel, where, mut, nth, i))
    return out


def render(sites) -> str:
    from audit_dispositions import DISPOSITIONS
    rows = []
    for rel, where, mut, nth, ln in sites:
        d = DISPOSITIONS.get((rel, where, mut, nth))
        cls, fields, ev, verdict, test = d if d else ("", "", "", "**NO VERDICT**", "")
        suffix = f" #{nth}" if nth > 1 else ""
        rows.append(f"| `{rel}:{ln}` | `{where}(){suffix}` | `{mut}` | {cls} | "
                    f"{fields} | {ev} | {verdict} | {test} |")
    open_n = sum(1 for r in rows if "🔴" in r)
    moved = sum(1 for r in rows if "➡️" in r)
    return ("<!-- GENERATED by specs/audit_manifest.py — do not hand-edit.\n"
            "     Verdicts live in specs/audit_dispositions.py.\n"
            "     Regenerate: python3 specs/audit_manifest.py --write\n"
            "     Verify:     python3 specs/audit_manifest.py --check -->\n\n"
            "# specs/0002 — store-mutator call-site manifest\n\n"
            f"**{len(sites)} call sites** across **{len(mutators())} mutators**, "
            "derived from the mutator interface in `store/base.py` rather than "
            "from recall or from a grep on assignment — **both of which were "
            "tried first and both of which were incomplete.**\n\n"
            f"**{len(sites) - open_n - moved} clean · {open_n} open · {moved} "
            "moved to another spec.** Clean sites are listed because a "
            "findings-only audit cannot demonstrate coverage — which is the "
            "claim the external review correctly refused to accept on the "
            "strength of an 11-row summary table.\n\n"
            "Identity is `(file, enclosing def, mutator, ordinal)`, **not the "
            "line number** — line numbers below are informational and never "
            "cause a `--check` failure.\n\n"
            "| call site | in | mutator | class | trust fields touched | "
            "evidence-bearing? | verdict | test |\n"
            "|---|---|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    sites = call_sites(mutators())
    if a.write:
        MANIFEST.write_text(render(sites))
        print(f"wrote {MANIFEST.relative_to(ROOT)}: {len(sites)} sites")
        return 0
    if a.check:
        if not MANIFEST.exists():
            print("manifest missing — run --write", file=sys.stderr)
            return 1
        from audit_dispositions import DISPOSITIONS
        want = {(r, w, m, n) for r, w, m, n, _ in sites}
        have = set(DISPOSITIONS)
        added, gone = want - have, have - want
        for k in sorted(added):
            print(f"NEW call site with no disposition: {k}", file=sys.stderr)
        for k in sorted(gone):
            print(f"disposition for a site that no longer exists: {k}", file=sys.stderr)
        blank = [k for k, v in DISPOSITIONS.items() if not v[3].strip()]
        for k in sorted(blank):
            print(f"no verdict recorded: {k}", file=sys.stderr)
        if added or gone or blank:
            print(f"\n{len(added)} new, {len(gone)} stale, {len(blank)} undecided. "
                  f"Every store mutation must carry a verdict and a test — that is "
                  f"what makes this a manifest rather than a claim.", file=sys.stderr)
            return 1
        if MANIFEST.exists() and MANIFEST.read_text() != render(sites):
            print("manifest is stale — regenerate with --write", file=sys.stderr)
            return 1
        print(f"manifest ok: {len(sites)} call sites, all dispositioned")
        return 0
    print(f"{len(sites)} call sites across {len(mutators())} mutators")
    for p, ln, mut, src in sites:
        print(f"  {p}:{ln}  {mut}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
