#!/usr/bin/env python3
"""The 0013 measuring instrument: the concrete v1→v2 confirmations migration.

**Draft-status instrument, not production.** `0013` is in review; only
`accepted` authorises implementation, so nothing here is imported by the store.
It exists because the round-9 M-Q1 ruling requires `0013` to be reviewed
**together with a real migration** — `0008`'s `confirmations` table — and a
migration you cannot run is not reviewable.

The round-3 architecture, in one paragraph: **there is exactly one planner.**
The instrument installs the draft v2 registry and the draft evidence artifact
into the production `0007` kernel and calls `open_versioned()` — the same
decision table the store executes, with `0013` supplying only the *older*-row
hook that `0007` §4 delegates to it. Migration is a dedicated offline
operation (`migrate_store`) requiring a `MigrationAuthority`; ordinary opening
(`open_or_migrate`) never migrates. What authorises a migration is **recorded
path evidence loaded from an immutable artifact**
(`specs/generated/migration_0013_evidence.json`), selected by runtime build
identity × source × declared-migration digest — never re-derived from the live
migration code, which is how round 3's `DELETE FROM edges` probe authorised
itself. Every outcome is a member of a closed vocabulary; raw SQLite and
protocol exceptions do not escape.

Run:  PYTHONPATH=src python3 specs/migrations_0013.py --simulate
      PYTHONPATH=src python3 specs/migrations_0013.py --write-evidence
      PYTHONPATH=src python3 specs/migrations_0013.py --check-evidence
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import sqlite3
import sys
import threading
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import NamedTuple

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from veracium.store import schema_version as sv          # noqa: E402
from veracium.store.schema_version import (              # noqa: E402
    REBUILDABLE, REQUIRED, SCHEMA_V1, SchemaObject, identity, manifest)

EVIDENCE_FILE = ROOT / "specs" / "generated" / "migration_0013_evidence.json"

# --------------------------------------------------------------------------
# the concrete schema change, derived from 0008 §6b–§6d

CONFIRMATIONS_DDL = """CREATE TABLE confirmations (
    id TEXT NOT NULL PRIMARY KEY, user_id TEXT NOT NULL, edge_id TEXT NOT NULL,
    confirmed_at TEXT NOT NULL, actor TEXT NOT NULL, call_path TEXT NOT NULL,
    correlation_id TEXT NOT NULL, request_digest TEXT NOT NULL,
    UNIQUE(user_id, correlation_id)
)"""
# Field-by-field from 0008 §6c: `confirmed_at` is the NORMALISED instant, never
# the caller's string; `actor` and `call_path` are closed-enum values.
#
# **`correlation_id` is NOT NULL — round 2 of this spec's review corrected v2.**
# 0008 §6c says an omitted correlation id is GENERATED by the library and
# returned as `str`, so a generated value must be persisted: a NULL row could
# never identify the original record on replay. "No replay protection across an
# unknown commit" comes from the caller not having retained the value, not from
# a NULL in storage. `UNIQUE(user_id, correlation_id)` is tenant-scoped per
# §6c's explicit "not global" ruling.
#
# **`id` is NOT NULL** — in an ordinary rowid table `TEXT PRIMARY KEY` accepts
# multiple NULLs (measured), and the id is store-generated (`c-<12 hex>`,
# matching every other veracium id).
#
# `request_digest` is the canonical-request digest replay compares against, so
# a same-id different-payload replay is an integrity conflict, not a lookup
# miss.

IX_CONFIRMATIONS_DDL = ("CREATE INDEX ix_confirmations_edge "
                        "ON confirmations(user_id, edge_id)")
# 0008 §6d: "indexed on edge_id" for confirmations_for(user_id, edge_id).
# Non-unique acceleration ⇒ REBUILDABLE under 0007 §4a-iii; the UNIQUE
# constraint above lives in the table DDL and is therefore in the digest.

SCHEMA_V2 = SCHEMA_V1 + (
    SchemaObject("table", "confirmations", CONFIRMATIONS_DDL, REQUIRED),
    SchemaObject("index", "ix_confirmations_edge", IX_CONFIRMATIONS_DDL,
                 REBUILDABLE),
)


class Migration(NamedTuple):
    """One declared step, n → n+1. Statements only — the callback model was
    withdrawn in 0007 round 5 (name mangling is not access control) and stays
    withdrawn."""
    from_version: int
    to_version: int
    statements: tuple


MIGRATION_1_TO_2 = Migration(1, 2, (CONFIRMATIONS_DDL, IX_CONFIRMATIONS_DDL))
# **The whole migration is two CREATE statements**, and that is a measured
# property worth the review's attention: because the change is purely additive,
# the migration's stored DDL is byte-identical to the constructor's, so
# MANIFESTS[2] has ONE digest with TWO provenances. The accepted-SET model
# (0007 §4a-v) is still exercised — both paths are generated and compared —
# but the ALTER-class divergence 0007 measured does not occur here.

SCHEMAS_DRAFT = {1: SCHEMA_V1, 2: SCHEMA_V2}
MIGRATIONS_DRAFT = {1: MIGRATION_1_TO_2}
DRAFT_SCHEMA_VERSION = 2


# --------------------------------------------------------------------------
# the review-tested execution rules (0007 rounds 3, 5–7; 0013 §4a–§4d)

_DENIED = (sqlite3.SQLITE_TRANSACTION, sqlite3.SQLITE_SAVEPOINT,
           sqlite3.SQLITE_ATTACH, sqlite3.SQLITE_DETACH, sqlite3.SQLITE_PRAGMA)


def _authorizer(action, _a1, _a2, db_name, _trigger):
    """Deny transaction control, pragmas, and anything outside `main`.

    `END`, `END TRANSACTION` and `RELEASE` all commit and a keyword blacklist
    missed all three; a TEMP trigger passed shape validation while silently
    deleting rows. Both measured in 0007's rounds. Defence against an
    *accidental declared statement* — migration statements are trusted code."""
    if action in _DENIED:
        return sqlite3.SQLITE_DENY
    if db_name not in (None, "main"):
        return sqlite3.SQLITE_DENY
    return sqlite3.SQLITE_OK


def apply_migration(conn: sqlite3.Connection, mig: Migration) -> None:
    """Execute a declared step inside the caller's open transaction.

    Authorizer installed around the statements and restored in `finally`;
    `sqlite_temp_master` asserted empty afterwards — an effect the persistent
    manifest cannot see is exactly what round 6 exploited."""
    # Round 3, finding 4: the one-transaction caveat was a calling convention,
    # not a boundary — on an autocommit connection a failed two-statement
    # migration left its first statement durably applied. The invariant is now
    # executable, and checked again after every statement.
    if not conn.in_transaction:
        raise RuntimeError("migration-protocol: a migration requires an "
                           "existing transaction; nothing may autocommit")
    conn.set_authorizer(_authorizer)
    try:
        for stmt in mig.statements:
            conn.execute(stmt)
            if not conn.in_transaction:
                raise RuntimeError("migration-protocol: transaction ended "
                                   "mid-migration")
    finally:
        # Python < 3.11 cannot DISABLE an authorizer: passing None only landed
        # in 3.11, and on 3.10 it leaves a callback that denies everything —
        # measured in CI as `not authorized` on every statement after the first
        # migration, on a matrix version the dev machine does not run. A
        # permissive callback is equivalent to disabled for this connection,
        # which §4b already requires to be Veracium-owned with no pre-existing
        # authorizer.
        conn.set_authorizer(lambda *_a: sqlite3.SQLITE_OK)
    leaked = [r[0] for r in conn.execute("SELECT name FROM sqlite_temp_master")]
    if leaked:
        raise RuntimeError(f"migration left temporary objects {leaked}")


def destination_problems(objs: dict, to_version: int,
                         schemas=None) -> list:
    """**Non-authorizing, deferred scaffolding** (round 3): capability describes
    a destination, it never authorises one — only exact identity and recorded
    evidence do. Kept for the first real ALTER's review, where the structural
    model gets its own round."""
    schemas = SCHEMAS_DRAFT if schemas is None else schemas
    declared = {o.key: o for o in schemas[to_version]}
    ref = sqlite3.connect(":memory:")
    for o in schemas[to_version]:
        ref.execute(o.ddl)
    want = identity(manifest(ref))
    ref.close()
    have = identity(objs) if not isinstance(next(iter(objs.values()), {}), dict) \
        else {f"{k[0]}:{k[1]}": v for k, v in objs.items()}
    problems = []
    for key, o in declared.items():
        skey = f"{key[0]}:{key[1]}"
        got = have.get(skey)
        if got is None:
            if o.policy == REBUILDABLE:
                continue
            problems.append(f"v{to_version} requires {skey}, absent")
        elif key[0] == "table":
            if got.get("columns") != want[skey].get("columns"):
                problems.append(f"{skey} columns differ from the declaration")
        elif got.get("sql") != o.ddl:
            problems.append(f"{skey} differs from its declaration")
    for skey in have:
        if tuple(skey.split(":", 1)) not in declared:
            problems.append(f"unapproved persistent object {skey}")
    return problems


def validate_registry(schemas=None, migrations=None, current=2) -> list:
    """Single-step model: adjacency, bound SCHEMA_VERSION, every version below
    current reachable. Cycles and duplicate routes are unrepresentable."""
    schemas = SCHEMAS_DRAFT if schemas is None else schemas
    migrations = MIGRATIONS_DRAFT if migrations is None else migrations
    problems = []
    if not isinstance(schemas, dict) or not schemas or \
            not isinstance(migrations, dict):
        return ["registry must be nonempty mappings"]
    if max(schemas) != current:
        problems.append(f"current {current} != max declared {max(schemas)}")
    if set(schemas) != set(range(1, current + 1)):
        problems.append(f"versions {sorted(schemas)} not contiguous 1..{current}")
    # Round 2, finding 6: EXACT key sets. A stray 2->3 step — an endpoint
    # beyond SCHEMA_VERSION — validated cleanly, because the loop checked each
    # present step without asking whether it should be present at all.
    if set(migrations) != set(range(1, current)):
        problems.append(f"migration keys {sorted(migrations)} are not exactly "
                        f"1..{current - 1}")
    for frm, mig in sorted(migrations.items()):
        if (mig.from_version, mig.to_version) != (frm, frm + 1):
            problems.append(f"step {frm}: not adjacent")
        if mig.to_version not in schemas or mig.from_version not in schemas:
            problems.append(f"step {frm}: endpoint not declared")
        if (not isinstance(mig.statements, tuple) or not mig.statements
                or not all(isinstance(x, str) and x.strip()
                           for x in mig.statements)):
            problems.append(f"step {frm}: statements must be a nonempty tuple "
                            f"of nonempty SQL — an empty migration is "
                            f"representable only for adversarial tests")
    return problems


# --------------------------------------------------------------------------
# digests and hashes (0013 §5c)

def canonical_migration_bytes(mig: Migration) -> bytes:
    """The reproducible encoding §5c's digest is defined over: domain-separated
    canonical JSON of the ordered statement list — "sha256 over the tuple" was
    not an algorithm without this."""
    return (b"veracium-migration-v1:"
            + json.dumps([mig.from_version, mig.to_version,
                          list(mig.statements)],
                         separators=(",", ":")).encode())


def migration_declaration_digest(mig: Migration) -> str:
    return hashlib.sha256(canonical_migration_bytes(mig)).hexdigest()


def full_manifest_hash(objs: dict) -> str:
    """EVERY object, rebuildables included (round 3, finding 2): the acceptance
    digest deliberately excludes them, so it can attest an output missing the
    very index §5 requires repaired — measured, digests equal while complete
    manifestations differ. Accepts either manifest form (typed-tuple keys) or
    identity form (string keys)."""
    ident = objs if all(isinstance(k, str) for k in objs) else identity(objs)
    return hashlib.sha256(
        json.dumps(ident, sort_keys=True,
                   separators=(",", ":")).encode()).hexdigest()


def _v2_constructor_objects() -> dict:
    cons = sqlite3.connect(":memory:")
    for o in SCHEMA_V2:
        cons.execute(o.ddl)
    objs = identity(manifest(cons))
    cons.close()
    return objs


# --------------------------------------------------------------------------
# the closed outcome vocabulary (0013 §5d)

MIGRATION_FAILURES = ("migration-required", "migration-evidence-missing",
                      "migration-failed", "migration-result-mismatch",
                      "migration-quiescence-required")
"""The closed failure model: hosts branch on these, plus 0007's REASONS."""

OUTCOMES = (frozenset({"created", "current", "adopted", "migrated"})
            | sv.REASONS | frozenset(MIGRATION_FAILURES))
"""Every value the two entry points can return. Free-form strings — round 3
measured `unexpected version 0` — are unrepresentable: `Outcome` refuses any
value outside this set."""


class Outcome(str):
    """A closed-vocabulary outcome that still `==`-compares as its string.

    Structured (round 3, finding 4): the branch value is the closed member;
    `diagnostic` carries detail for logs and bug reports and never leaks into
    the value hosts branch on."""
    __slots__ = ("diagnostic",)

    def __new__(cls, value: str, diagnostic: str | None = None):
        if value not in OUTCOMES:
            raise ValueError(f"{value!r} is not in the closed outcome "
                             f"vocabulary")
        out = str.__new__(cls, value)
        out.diagnostic = diagnostic
        return out


class MigrationRefused(Exception):
    """Internal control flow for the migration-specific closed reasons; mapped
    to an `Outcome` at the entry points, never shown to callers raw."""

    def __init__(self, reason: str, diagnostic: str | None = None):
        assert reason in MIGRATION_FAILURES, reason
        self.reason, self.diagnostic = reason, diagnostic
        super().__init__(f"{reason}: {diagnostic or ''}")


# --------------------------------------------------------------------------
# the offline-boundary attestation (0013 §5b)

class MigrationAuthority(NamedTuple):
    """The explicit offline-boundary attestation.

    A library cannot infer host quiescence, so the HOST asserts it — old
    processes stopped, admission closed, backup taken — and the migration
    refuses without it. Round 3 tightened the shape: the assertion **binds**
    what it authorises (this store, this reviewed migration, this operation)
    and every field is exact-typed — `quiesced=1` with `backup_ref=object()`
    migrated under v4's NamedTuple. Production authorities are minted by
    release tooling and additionally bind the release/deployment identity;
    that binding is recorded in §5b as an implementation obligation."""
    quiesced: bool          # exactly True — the host's quiescence attestation
    backup_ref: str         # where the pre-migration backup lives
    store_path: str         # the one store this authority covers
    migration_digest: str   # migration_declaration_digest of the reviewed step
    operation_id: str       # host-side identity for this migration operation
    issued_at: str          # RFC 3339 UTC, read from the clock at issuance


def make_authority(path, backup_ref: str = "draft-backup",
                   migration: Migration | None = None) -> MigrationAuthority:
    """Draft convenience for hosts and tests; reads the module's current
    migration so a test that patches `MIGRATION_1_TO_2` mints an authority for
    what it patched in — the authority attests the *reviewed statements*, and
    the evidence gate is what catches statements no evidence covers."""
    mig = MIGRATION_1_TO_2 if migration is None else migration
    return MigrationAuthority(
        quiesced=True, backup_ref=backup_ref, store_path=str(path),
        migration_digest=migration_declaration_digest(mig),
        operation_id=f"op-{uuid.uuid4()}",
        issued_at=datetime.now(timezone.utc).isoformat())


def authority_problems(a, spath: str, expected_digest: str) -> list:
    """Exact types, exact bindings; total over any input."""
    if not isinstance(a, MigrationAuthority):
        return [f"authority is {type(a).__name__}, not a MigrationAuthority"]
    problems = []
    if type(a.quiesced) is not bool:
        problems.append(f"quiesced must be bool, is {type(a.quiesced).__name__}")
    elif a.quiesced is not True:
        problems.append("the host has not attested quiescence")
    for field in ("backup_ref", "store_path", "migration_digest",
                  "operation_id", "issued_at"):
        v = getattr(a, field)
        if not isinstance(v, str) or not v.strip():
            problems.append(f"{field} must be a nonempty string, is "
                            f"{type(v).__name__}")
    if isinstance(a.store_path, str) and a.store_path != spath:
        problems.append(f"authority covers store {a.store_path!r}, "
                        f"not {spath!r}")
    if isinstance(a.migration_digest, str) and \
            a.migration_digest != expected_digest:
        problems.append("authority attests a different migration declaration "
                        "than the one registered for this step")
    return problems


# --------------------------------------------------------------------------
# migration-runtime qualification (round 3, finding 3)

AUTHORIZER_PROBE_KEYS = frozenset({
    "authorizer_api_available", "denies_begin", "denies_commit", "denies_end",
    "denies_savepoint", "denies_release", "denies_pragma", "denies_attach",
    "denies_detach", "denies_temp_schema", "authorizer_restored"})
"""The closed confinement vocabulary. 0007's runtime identity deliberately has
no authorizer probe — migrations left its scope in v10 — so its qualification
cannot attest the behaviours `apply_migration` leans on. These are ALL
required: a runtime failing any of them may execute a migration outside the
declared confinement, so it is not qualified to migrate at all."""

MIGRATION_EVIDENCE_ALGORITHM = 1


def _denied_by_authorizer(setup: tuple, stmt: str) -> bool:
    c = sqlite3.connect(":memory:")
    c.isolation_level = None
    try:
        for s in setup:
            c.execute(s)
        try:
            c.set_authorizer(_authorizer)
        except Exception:
            return False
        try:
            c.execute(stmt)
            return False
        except sqlite3.DatabaseError:
            return True
    finally:
        c.close()


def authorizer_probes() -> dict:
    """Measure the confinement behaviours on THIS runtime — the generation-time
    source of the migration-runtime record, and the live half of the
    consumption-time comparison."""
    out = {"authorizer_api_available":
           hasattr(sqlite3.Connection, "set_authorizer")}
    out["denies_begin"] = _denied_by_authorizer((), "BEGIN")
    out["denies_commit"] = _denied_by_authorizer(("BEGIN IMMEDIATE",), "COMMIT")
    out["denies_end"] = _denied_by_authorizer(("BEGIN IMMEDIATE",), "END")
    out["denies_savepoint"] = _denied_by_authorizer(
        ("BEGIN IMMEDIATE",), "SAVEPOINT s1")
    out["denies_release"] = _denied_by_authorizer(
        ("BEGIN IMMEDIATE",), "RELEASE s1")
    out["denies_pragma"] = _denied_by_authorizer((), "PRAGMA user_version = 7")
    out["denies_attach"] = _denied_by_authorizer((), "ATTACH ':memory:' AS side")
    out["denies_detach"] = _denied_by_authorizer(
        ("ATTACH ':memory:' AS side",), "DETACH side")
    out["denies_temp_schema"] = _denied_by_authorizer(
        ("BEGIN IMMEDIATE",), "CREATE TEMP TABLE tprobe (x)")

    def _restored() -> bool:
        c = sqlite3.connect(":memory:")
        c.isolation_level = None
        try:
            c.set_authorizer(_authorizer)
            try:
                c.execute("PRAGMA user_version = 3")
                return False                       # was never denied
            except sqlite3.DatabaseError:
                pass
            c.set_authorizer(lambda *_a: sqlite3.SQLITE_OK)
            c.execute("PRAGMA user_version = 3")
            return c.execute("PRAGMA user_version").fetchone()[0] == 3
        except Exception:
            return False
        finally:
            c.close()
    out["authorizer_restored"] = _restored()
    return out


def migration_runtime_record_problems(rec) -> list:
    """Closed structure and required behaviours; total over any input."""
    if not isinstance(rec, dict):
        return [f"migration-runtime record is {type(rec).__name__}"]
    problems = []
    want = {"sqlite_version", "source_id", "features",
            "migration_evidence_algorithm", "authorizer_probes"}
    if set(rec) != want:
        return [f"record fields {sorted(rec)} are not exactly {sorted(want)}"]
    for f in ("sqlite_version", "source_id"):
        if not isinstance(rec[f], str) or not rec[f]:
            problems.append(f"{f!r} must be a nonempty string")
    if not isinstance(rec["features"], dict):
        problems.append("'features' must be a mapping")
    if type(rec["migration_evidence_algorithm"]) is not int:
        problems.append("'migration_evidence_algorithm' must be an int")
    probes = rec["authorizer_probes"]
    if not isinstance(probes, dict):
        return problems + ["'authorizer_probes' must be a mapping"]
    if set(probes) != AUTHORIZER_PROBE_KEYS:
        problems.append(f"probe keys {sorted(probes)} are not exactly "
                        f"{sorted(AUTHORIZER_PROBE_KEYS)}")
    for k, v in probes.items():
        if type(v) is not bool:
            problems.append(f"probe {k!r} is {type(v).__name__}, not bool")
        elif v is not True:
            problems.append(f"runtime fails required confinement behaviour "
                            f"{k!r}")
    return problems


def migration_runtime_supported(art) -> bool:
    """Both halves of finding 3's correction: a RECORDED qualification for this
    build identity, and the recorded behaviours REPRODUCED live — mirroring how
    `runtime_supported()` re-derives constructor manifestations rather than
    trusting the record. Total, fail-closed."""
    try:
        if not isinstance(art, dict):
            return False
        records = art.get("migration_runtimes")
        if not isinstance(records, list):
            return False
        me = sv.build_identity(sv.runtime_identity())
        hits = [r for r in records
                if isinstance(r, dict)
                and r.get("migration_evidence_algorithm")
                == MIGRATION_EVIDENCE_ALGORITHM
                and not migration_runtime_record_problems(r)
                and sv.build_identity(r) == me]
        if len(hits) != 1:
            return False
        return authorizer_probes() == hits[0]["authorizer_probes"]
    except Exception:
        return False


# --------------------------------------------------------------------------
# the draft evidence artifact: loaded, validated, consumed — never re-derived
# at decision time (round 3, finding 2)

def _load_artifact():
    try:
        return json.loads(EVIDENCE_FILE.read_text())
    except (OSError, ValueError):
        return None


ARTIFACT_FIELDS = frozenset({
    "artifact", "migration_evidence_algorithm", "manifest_algorithm",
    "draft_schema_version", "generated_at", "schema_versions",
    "legacy_base_versions", "runtimes", "migration_runtimes", "paths"})

PATH_RECORD_FIELDS = frozenset({
    "migration_evidence_algorithm", "manifest_algorithm", "runtime",
    "from_version", "to_version", "source_acceptance_digest",
    "source_full_manifest_hash", "output_acceptance_digest",
    "output_full_manifest_hash", "output_manifestation",
    "migration_declaration_digest", "provenance"})


def schema_evidence_problems(art) -> list:
    """The parts of the artifact that feed the `0007` kernel — draft accepted
    manifests, draft runtime records, legacy bases. Any problem here poisons
    the whole context (0007 round 12's rule: a malformed current record is
    evidence of tampering, and the safe reading is "unqualified").

    Must run under the draft registry patch: the validators it delegates to
    read the module registry."""
    if not isinstance(art, dict):
        return [f"artifact is {type(art).__name__}, not a mapping"]
    problems = []
    if set(art) != ARTIFACT_FIELDS:
        return [f"artifact fields {sorted(art)} are not exactly "
                f"{sorted(ARTIFACT_FIELDS)}"]
    if art.get("manifest_algorithm") != sv.MANIFEST_ALGORITHM:
        problems.append(f"artifact manifest algorithm "
                        f"{art.get('manifest_algorithm')!r} is not "
                        f"{sv.MANIFEST_ALGORITHM}")
    if art.get("migration_evidence_algorithm") != MIGRATION_EVIDENCE_ALGORITHM:
        problems.append("artifact migration-evidence algorithm is not current")
    if art.get("draft_schema_version") != DRAFT_SCHEMA_VERSION:
        problems.append("artifact draft schema version disagrees with the "
                        "registry")
    versions = art.get("schema_versions")
    if not isinstance(versions, dict) or \
            set(versions) != {str(v) for v in SCHEMAS_DRAFT}:
        problems.append("schema_versions must cover exactly the draft registry")
    else:
        for v, rec in sorted(versions.items()):
            if not isinstance(rec, dict) or \
                    not isinstance(rec.get("accepted"), list) or \
                    not rec["accepted"]:
                problems.append(f"version {v}: no accepted manifests")
                continue
            for a in rec["accepted"]:
                if not isinstance(a, dict) or set(a) != {"digest", "objects",
                                                         "provenance"}:
                    problems.append(f"version {v}: accepted entry is not "
                                    f"exactly digest/objects/provenance")
                    continue
                problems += [f"version {v}: {p}" for p in
                             sv.manifestation_problems(a["objects"], int(v))]
                if sv._digest_of_identity(a["objects"], int(v)) != a["digest"]:
                    problems.append(f"version {v}: accepted objects do not "
                                    f"hash to their recorded digest")
    legacy = art.get("legacy_base_versions")
    if not isinstance(legacy, list) or \
            not all(type(v) is int and v in SCHEMAS_DRAFT for v in legacy):
        problems.append("legacy_base_versions must be declared draft versions")
    runtimes = art.get("runtimes")
    if not isinstance(runtimes, list):
        problems.append("runtimes must be a list")
    else:
        problems += sv.artifact_problems(runtimes)
        if not sv.active_records(runtimes):
            problems.append("no active runtime record; nothing is qualified")
    if not isinstance(art.get("migration_runtimes"), list):
        problems.append("migration_runtimes must be a list")
    if not isinstance(art.get("paths"), list):
        problems.append("paths must be a list")
    return problems


def path_record_problems(rec, art) -> list:
    """One §5c record: closed structure, and the record-level consistency
    rules round 3 required — the recorded output must hash to BOTH its
    recorded hashes, and the source identifiers must resolve to exactly one
    accepted source manifestation."""
    if not isinstance(rec, dict):
        return [f"path record is {type(rec).__name__}"]
    if set(rec) != PATH_RECORD_FIELDS:
        return [f"path record fields {sorted(rec)} are not exactly "
                f"{sorted(PATH_RECORD_FIELDS)}"]
    problems = []
    if rec["manifest_algorithm"] != sv.MANIFEST_ALGORITHM or \
            rec["migration_evidence_algorithm"] != MIGRATION_EVIDENCE_ALGORITHM:
        problems.append("path record algorithms are not current")
    rt = rec["runtime"]
    if not isinstance(rt, dict) or \
            set(rt) != {"sqlite_version", "source_id", "features"}:
        problems.append("path record runtime identity is malformed")
    frm, to = rec["from_version"], rec["to_version"]
    if type(frm) is not int or type(to) is not int or to != frm + 1 or \
            frm not in SCHEMAS_DRAFT or to not in SCHEMAS_DRAFT:
        problems.append(f"path record step {frm!r}→{to!r} is not an adjacent "
                        f"declared pair")
        return problems
    for f in ("source_acceptance_digest", "source_full_manifest_hash",
              "output_acceptance_digest", "output_full_manifest_hash",
              "migration_declaration_digest", "provenance"):
        if not isinstance(rec[f], str) or not rec[f]:
            problems.append(f"path record field {f!r} must be a nonempty "
                            f"string")
    out = rec["output_manifestation"]
    if not isinstance(out, dict):
        problems.append("output_manifestation must be a mapping")
        return problems
    problems += [f"output: {p}" for p in sv.manifestation_problems(out, to)]
    if sv._digest_of_identity(out, to) != rec["output_acceptance_digest"]:
        problems.append("recorded output does not hash to its recorded "
                        "acceptance digest")
    if full_manifest_hash(out) != rec["output_full_manifest_hash"]:
        problems.append("recorded output does not hash to its recorded "
                        "full-manifest hash")
    versions = art.get("schema_versions", {}) if isinstance(art, dict) else {}

    def _resolves(version: int, dig, fmh) -> int:
        vrec = versions.get(str(version), {})
        accepted = vrec.get("accepted", []) if isinstance(vrec, dict) else []
        return len([a for a in accepted if isinstance(a, dict)
                    and a.get("digest") == dig
                    and full_manifest_hash(a.get("objects", {})) == fmh])

    n = _resolves(frm, rec["source_acceptance_digest"],
                  rec["source_full_manifest_hash"])
    if n != 1:
        problems.append(f"source identifiers resolve to {n} accepted "
                        f"v{frm} manifestations, not exactly one")
    # Symmetric with the source rule: a migration output that is not an
    # accepted destination manifestation is exactly what 0007's accepted-SET
    # model exists to refuse — an evidenced-but-unaccepted output must fail at
    # the artifact, not at the stamp.
    n = _resolves(to, rec["output_acceptance_digest"],
                  rec["output_full_manifest_hash"])
    if n != 1:
        problems.append(f"output identifiers resolve to {n} accepted "
                        f"v{to} manifestations, not exactly one")
    return problems


def _path_key(rec) -> tuple:
    return (sv.build_identity(rec.get("runtime", {})), rec.get("from_version"),
            rec.get("to_version"), rec.get("source_acceptance_digest"),
            rec.get("source_full_manifest_hash"),
            rec.get("migration_declaration_digest"))


def path_evidence_problems(art) -> list:
    """Artifact-level: every current-algorithm path record valid, no duplicate
    and no contradictory records under the same selection key."""
    if not isinstance(art, dict) or not isinstance(art.get("paths"), list):
        return ["artifact has no path-record list"]
    problems, seen = [], {}
    for rec in art["paths"]:
        if isinstance(rec, dict) and rec.get("migration_evidence_algorithm") \
                != MIGRATION_EVIDENCE_ALGORITHM:
            continue                       # superseded algorithm: contributes
        problems += path_record_problems(rec, art)     # nothing, poisons nothing
        if not isinstance(rec, dict):
            continue
        key = _path_key(rec)
        if key in seen:
            if seen[key] != rec.get("output_full_manifest_hash"):
                problems.append("two path records share a selection key but "
                                "declare different outputs — the artifact is "
                                "self-contradictory and neither can be trusted")
            else:
                problems.append("duplicate path record for one selection key")
        seen[key] = rec.get("output_full_manifest_hash")
    return problems


def expected_path_problems(art) -> list:
    """Exact cardinality against the LIVE registry (round 3): for the current
    runtime, every (declared step × accepted source manifestation) pair has
    exactly one record, and no current-algorithm record exists outside that
    set. An altered migration digests differently, so its expected pair has
    zero records — which is precisely the self-authorization hole this check
    closes."""
    problems = []
    me = sv.build_identity(sv.runtime_identity())
    current = [r for r in art.get("paths", []) if isinstance(r, dict)
               and r.get("migration_evidence_algorithm")
               == MIGRATION_EVIDENCE_ALGORITHM
               and sv.build_identity(r.get("runtime", {})) == me]
    versions = art.get("schema_versions", {})
    expected = set()
    for frm, mig in sorted(MIGRATIONS_DRAFT.items()):
        src = versions.get(str(frm), {})
        for a in src.get("accepted", []) if isinstance(src, dict) else []:
            expected.add((me, frm, mig.to_version, a.get("digest"),
                          full_manifest_hash(a.get("objects", {})),
                          migration_declaration_digest(mig)))
    have = {}
    for r in current:
        have[_path_key(r)] = have.get(_path_key(r), 0) + 1
    for key in sorted(expected - set(have), key=repr):
        problems.append(f"no path-evidence record for expected combination "
                        f"(step {key[1]}→{key[2]})")
    for key in sorted(set(have) - expected, key=repr):
        problems.append(f"path-evidence record exists for a combination the "
                        f"live registry does not declare (step "
                        f"{key[1]}→{key[2]})")
    for key, n in sorted(have.items(), key=repr):
        if n > 1:
            problems.append(f"{n} path-evidence records for one combination")
    return problems


# --------------------------------------------------------------------------
# the draft context: the 0007 kernel, running as the v2 build would ship it

_DRAFT_LOCK = threading.Lock()
_DRAFT = {"depth": 0, "saved": None, "artifact": None}


@contextmanager
def _draft():
    """Install the draft registry and evidence into the production kernel.

    This is how the instrument runs **the** planner rather than a second one
    (round 3, finding 1): `sv.open_versioned` executes with `SCHEMAS` = the
    draft registry, `SCHEMA_VERSION` = 2, and every evidence accessor answering
    from the loaded artifact — exactly the state a v2 build ships as package
    data. A malformed or missing artifact installs EMPTY evidence, so every
    gate fails closed to `unsupported-sqlite`. Reference-counted under a lock:
    concurrent openers (the M-Q2 race) nest safely because every entry installs
    identical values."""
    with _DRAFT_LOCK:
        if _DRAFT["depth"] == 0:
            art = _load_artifact()
            _DRAFT["saved"] = {
                "SCHEMAS": sv.SCHEMAS,
                "SCHEMA_VERSION": sv.SCHEMA_VERSION,
                "version_records": sv.version_records,
                "legacy_base_versions": sv.legacy_base_versions,
                "override": list(sv._RUNTIME_OVERRIDE),
            }
            sv.SCHEMAS = dict(SCHEMAS_DRAFT)
            sv.SCHEMA_VERSION = DRAFT_SCHEMA_VERSION
            if art is not None and not schema_evidence_problems(art):
                versions = art["schema_versions"]
                legacy = frozenset(art["legacy_base_versions"])
                sv._RUNTIME_OVERRIDE[:] = [art["runtimes"]]
            else:
                versions, legacy = {}, frozenset()
                sv._RUNTIME_OVERRIDE[:] = [[]]
            sv.version_records = lambda: versions
            sv.legacy_base_versions = lambda: legacy
            _DRAFT["artifact"] = art
        _DRAFT["depth"] += 1
        art = _DRAFT["artifact"]
    try:
        yield art
    finally:
        with _DRAFT_LOCK:
            _DRAFT["depth"] -= 1
            if _DRAFT["depth"] == 0:
                saved = _DRAFT["saved"]
                sv.SCHEMAS = saved["SCHEMAS"]
                sv.SCHEMA_VERSION = saved["SCHEMA_VERSION"]
                sv.version_records = saved["version_records"]
                sv.legacy_base_versions = saved["legacy_base_versions"]
                sv._RUNTIME_OVERRIDE[:] = saved["override"]
                _DRAFT["saved"] = _DRAFT["artifact"] = None


# --------------------------------------------------------------------------
# the older-row hooks and the two entry points (0013 §5b, §5d)

def _accepted_at(art, version: int) -> set:
    rec = art.get("schema_versions", {}).get(str(version), {})
    return {a.get("digest") for a in rec.get("accepted", [])
            if isinstance(a, dict)}


def _classify_source(art, conn, spath, found, objs, base) -> None:
    """The source must BE an accepted older manifestation before anything is
    said about migrating it — round 3 measured a stamped v1 store with an
    unauthorized extra table answering `migration-required`, which promises a
    migration path for a store that has none."""
    if sv.digest(objs, base) not in _accepted_at(art, base):
        raise sv.StoreVersionError(
            spath, found, sv.SCHEMA_VERSION, "stamped-shape-mismatch",
            diff=sv._shape_diff(objs, base))


def _refusing_hook(art):
    """Ordinary opening's older row: classify the source, then refuse.
    Ordinary opening cannot initiate migration — that is the offline boundary,
    stated as a mechanism."""
    def hook(conn, spath, found, objs, base):
        _classify_source(art, conn, spath, found, objs, base)
        raise MigrationRefused(
            "migration-required",
            f"store is schema v{base}; ordinary opening never migrates — "
            f"run the dedicated offline migration operation (§5b)")
    return hook


def _migrating_hook(art, authority):
    """The dedicated offline operation's older row: classify, check the
    authority, select the recorded path evidence, execute, compare the
    complete output against the record, and only then stamp. Every failure is
    a closed outcome; the kernel's transaction rolls anything partial back."""
    def hook(conn, spath, found, objs, base):
        _classify_source(art, conn, spath, found, objs, base)
        step = MIGRATIONS_DRAFT.get(base)
        if step is None or step.to_version != sv.SCHEMA_VERSION:
            # Adjacent single-step only; the skipped-release planner is
            # deferred to the first spec that needs two real steps.
            raise MigrationRefused(
                "migration-required",
                f"no adjacent declared step migrates v{base} to "
                f"v{sv.SCHEMA_VERSION}")
        probs = authority_problems(authority, spath,
                                   migration_declaration_digest(step))
        if probs:
            raise MigrationRefused("migration-quiescence-required",
                                   "; ".join(probs))
        reg = validate_registry(current=sv.SCHEMA_VERSION)
        if reg:
            raise MigrationRefused("migration-evidence-missing",
                                   "the migration registry is malformed: "
                                   + "; ".join(reg))
        # Source rebuildable drift is repaired at the SOURCE version before
        # hashing, so the full-manifest comparison is against the accepted
        # source manifestation, not against incidental index drift.
        if sv.drift(objs, base):
            sv._repair_drift(conn, base)
            objs = manifest(conn)
            if sv.digest(objs, base) not in _accepted_at(art, base) \
                    or sv.drift(objs, base):
                raise sv.StoreVersionError(
                    spath, found, sv.SCHEMA_VERSION, "stamped-shape-mismatch",
                    diff=sv._shape_diff(objs, base))
        rec = _select_path_record(art, base, objs, step)
        try:
            apply_migration(conn, step)
        except (sqlite3.Error, RuntimeError) as exc:
            raise MigrationRefused("migration-failed", repr(exc)) from exc
        try:
            if sv.drift(manifest(conn), step.to_version):
                sv._repair_drift(conn, step.to_version)
            out_objs = manifest(conn)
        except (sqlite3.Error, RuntimeError) as exc:
            raise MigrationRefused("migration-failed", repr(exc)) from exc
        # The recorded prospective output authorises the stamp: complete
        # manifestation, acceptance digest AND full-manifest hash must all
        # match what the evidence job recorded (round 3, finding 2).
        if not (identity(out_objs) == rec["output_manifestation"]
                and sv.digest(out_objs, step.to_version)
                == rec["output_acceptance_digest"]
                and full_manifest_hash(out_objs)
                == rec["output_full_manifest_hash"]):
            raise MigrationRefused(
                "migration-result-mismatch",
                "the executed migration did not reproduce the recorded "
                "output manifestation; nothing was stamped")
        conn.execute(f"PRAGMA user_version = {step.to_version}")
    return hook


def _select_path_record(art, base, objs, step) -> dict:
    """Selection over RECORDED evidence, by the full key round 3 froze:
    runtime build identity × source version × source acceptance digest ×
    source full-manifest hash × destination version × migration declaration
    digest. Exactly one record or the migration does not run."""
    probs = path_evidence_problems(art) + expected_path_problems(art)
    if probs:
        raise MigrationRefused("migration-evidence-missing",
                               "; ".join(probs[:4]))
    me = sv.build_identity(sv.runtime_identity())
    want = (me, base, step.to_version, sv.digest(objs, base),
            full_manifest_hash(objs), migration_declaration_digest(step))
    hits = [r for r in art["paths"] if isinstance(r, dict)
            and r.get("migration_evidence_algorithm")
            == MIGRATION_EVIDENCE_ALGORITHM and _path_key(r) == want]
    if len(hits) != 1:
        raise MigrationRefused(
            "migration-evidence-missing",
            f"{len(hits)} recorded path-evidence records match this runtime, "
            f"source and migration declaration; a migration no recorded "
            f"evidence covers must not run")
    return hits[0]


def _run(path, busy_timeout_ms: int, migrating: bool,
         authority=None) -> Outcome:
    with _draft() as art:
        try:
            if not sv.runtime_supported():
                return Outcome(
                    "unsupported-sqlite",
                    f"sqlite {sqlite3.sqlite_version} has no qualified "
                    f"schema-runtime record in the draft evidence; "
                    f"regenerate it here (migrations_0013.py "
                    f"--write-evidence)")
            if migrating and not migration_runtime_supported(art):
                return Outcome(
                    "unsupported-sqlite",
                    "this runtime has no migration-confinement "
                    "qualification (or its recorded authorizer behaviours "
                    "do not reproduce here); migration refuses before "
                    "touching the store")
            hook = (_migrating_hook(art, authority) if migrating
                    else _refusing_hook(art))
            conn = sqlite3.connect(path, timeout=busy_timeout_ms / 1000)
            conn.isolation_level = None
            try:
                conn.execute(f"PRAGMA busy_timeout = {int(busy_timeout_ms)}")
                label = sv.open_versioned(conn, str(path), allow_adopt=True,
                                          older=hook)
                return Outcome(label)
            finally:
                conn.close()
        except sv.StoreVersionError as e:
            return Outcome(e.reason, diagnostic=e.diff)
        except MigrationRefused as e:
            return Outcome(e.reason, diagnostic=e.diagnostic)


def open_or_migrate(path, busy_timeout_ms: int = 5000) -> Outcome:
    """Ordinary opening: the full inherited `0007` table, and the older row
    REFUSES — `migration-required` for an accepted older source, the ordinary
    shape reasons otherwise. No authority parameter exists here: the migration
    operation is not exposed through tenant-facing opening (round 3)."""
    return _run(path, busy_timeout_ms, migrating=False)


def migrate_store(path, authority: MigrationAuthority,
                  busy_timeout_ms: int = 5000) -> Outcome:
    """The dedicated offline migration operation (§5b): same planner, with the
    older row migrating under recorded evidence and an explicit, bound,
    exact-typed host attestation."""
    return _run(path, busy_timeout_ms, migrating=True, authority=authority)


# --------------------------------------------------------------------------
# evidence generation and verification (the M11/M12 draft forms)

def _constructor_accepted(version: int) -> dict:
    c = sqlite3.connect(":memory:")
    for o in SCHEMAS_DRAFT[version]:
        c.execute(o.ddl)
    objs = identity(manifest(c))
    c.close()
    return {"digest": sv._digest_of_identity(objs, version), "objects": objs,
            "provenance": f"constructor v{version}"}


def _generate_artifact() -> tuple:
    """Build the prospective artifact by MEASURING this runtime: constructor
    manifestations, authorizer behaviours, and one executed migration per
    (declared step × accepted source). Returns (artifact, problems) — problems
    refuse generation, they are never written."""
    problems = []
    me = sv.runtime_identity()
    versions, legacy_src = {}, sv.legacy_base_versions
    with _registry():
        reg = validate_registry(current=sv.SCHEMA_VERSION)
        if reg:
            return None, [f"registry: {p}" for p in reg]
        for v in sorted(SCHEMAS_DRAFT):
            versions[str(v)] = {"accepted": [_constructor_accepted(v)]}
        runtime_rec = {
            **me, "manifest_algorithm": sv.MANIFEST_ALGORITHM,
            "schema_version": DRAFT_SCHEMA_VERSION,
            "constructor_digests": {
                str(v): versions[str(v)]["accepted"][0]["digest"]
                for v in SCHEMAS_DRAFT},
            "manifestations": {
                f"constructor v{v}": versions[str(v)]["accepted"][0]["objects"]
                for v in SCHEMAS_DRAFT},
        }
        problems += [f"runtime record: {p}"
                     for p in sv.runtime_record_problems(runtime_rec)]
        probes = authorizer_probes()
        mig_rec = {"sqlite_version": me["sqlite_version"],
                   "source_id": me["source_id"], "features": me["features"],
                   "migration_evidence_algorithm":
                       MIGRATION_EVIDENCE_ALGORITHM,
                   "authorizer_probes": probes}
        problems += [f"migration runtime: {p}"
                     for p in migration_runtime_record_problems(mig_rec)]
        paths = []
        for frm, mig in sorted(MIGRATIONS_DRAFT.items()):
            for a in versions[str(frm)]["accepted"]:
                c = sqlite3.connect(":memory:")
                c.isolation_level = None
                try:
                    for o in SCHEMAS_DRAFT[frm]:
                        c.execute(o.ddl)
                    c.execute("BEGIN IMMEDIATE")
                    apply_migration(c, mig)
                    if sv.drift(manifest(c), mig.to_version):
                        sv._repair_drift(c, mig.to_version)
                    out = identity(manifest(c))
                    c.execute("ROLLBACK")
                except (sqlite3.Error, RuntimeError) as exc:
                    problems.append(f"step {frm}: prospective execution "
                                    f"failed: {exc!r}")
                    continue
                finally:
                    c.close()
                paths.append({
                    "migration_evidence_algorithm":
                        MIGRATION_EVIDENCE_ALGORITHM,
                    "manifest_algorithm": sv.MANIFEST_ALGORITHM,
                    "runtime": {"sqlite_version": me["sqlite_version"],
                                "source_id": me["source_id"],
                                "features": me["features"]},
                    "from_version": frm, "to_version": mig.to_version,
                    "source_acceptance_digest": a["digest"],
                    "source_full_manifest_hash":
                        full_manifest_hash(a["objects"]),
                    "output_acceptance_digest":
                        sv._digest_of_identity(out, mig.to_version),
                    "output_full_manifest_hash": full_manifest_hash(out),
                    "output_manifestation": out,
                    "migration_declaration_digest":
                        migration_declaration_digest(mig),
                    "provenance": f"migrations_0013.py --write-evidence on "
                                  f"sqlite {me['sqlite_version']}",
                })
    art = {
        "artifact": "specs/0013 draft evidence",
        "migration_evidence_algorithm": MIGRATION_EVIDENCE_ALGORITHM,
        "manifest_algorithm": sv.MANIFEST_ALGORITHM,
        "draft_schema_version": DRAFT_SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "schema_versions": versions,
        "legacy_base_versions": sorted(legacy_src()),
        "runtimes": [runtime_rec],
        "migration_runtimes": [mig_rec],
        "paths": paths,
    }
    with _registry():
        problems += [f"artifact: {p}" for p in schema_evidence_problems(art)]
        problems += [f"paths: {p}" for p in path_evidence_problems(art)]
        problems += [f"paths: {p}" for p in expected_path_problems(art)]
    return art, problems


@contextmanager
def _registry():
    """Registry-only patch (no evidence install) — for generation and
    verification, which measure the runtime rather than consult the file."""
    with _DRAFT_LOCK:
        assert _DRAFT["depth"] == 0, "generation inside an open draft context"
        saved = sv.SCHEMAS, sv.SCHEMA_VERSION
        sv.SCHEMAS = dict(SCHEMAS_DRAFT)
        sv.SCHEMA_VERSION = DRAFT_SCHEMA_VERSION
    try:
        yield
    finally:
        with _DRAFT_LOCK:
            sv.SCHEMAS, sv.SCHEMA_VERSION = saved


def write_evidence() -> int:
    art, problems = _generate_artifact()
    if problems:
        print("refusing to record evidence; this runtime does not qualify:")
        for p in problems:
            print(f"  - {p}")
        return 1
    tmp = EVIDENCE_FILE.with_suffix(".json.tmp")
    try:
        tmp.write_text(json.dumps(art, indent=1, sort_keys=True) + "\n")
        os.replace(tmp, EVIDENCE_FILE)
    finally:
        if tmp.exists():                      # v12's lesson: no stray .tmp
            tmp.unlink()
    print(f"recorded {EVIDENCE_FILE.relative_to(ROOT)} for sqlite "
          f"{sqlite3.sqlite_version}: {len(art['paths'])} path record(s), "
          f"1 runtime, 1 migration-runtime qualification")
    return 0


def check_evidence() -> int:
    art = _load_artifact()
    if art is None:
        print(f"missing or unreadable {EVIDENCE_FILE.relative_to(ROOT)}")
        return 1
    with _registry():
        problems = schema_evidence_problems(art)
        problems += path_evidence_problems(art)
        recorded = {sv.build_identity(r) for r in
                    sv.active_records(art.get("runtimes", []))}
    if problems:
        for p in problems:
            print(f"  - {p}")
        return 1
    if sv.build_identity(sv.runtime_identity()) not in recorded:
        print(f"artifact records a different runtime identity than this "
              f"process (sqlite {sqlite3.sqlite_version}); structural checks "
              f"pass, re-derivation needs the recording runtime")
        return 2
    expected, gen_problems = _generate_artifact()
    if gen_problems:
        for p in gen_problems:
            print(f"  - regeneration: {p}")
        return 1
    drop = {"generated_at"}
    a = {k: v for k, v in art.items() if k not in drop}
    b = {k: v for k, v in expected.items() if k not in drop}
    if a != b:
        keys = [k for k in a if a.get(k) != b.get(k)]
        print(f"artifact does not reproduce on this runtime; differing "
              f"sections: {keys}")
        return 1
    print("evidence artifact reproduces exactly on this runtime")
    return 0


# --------------------------------------------------------------------------

def simulate() -> int:
    """End to end, on a populated store: refuse ordinarily, migrate under
    authority, reopen current, data intact, 0008's uniqueness demonstrated.
    On an unqualified runtime: report the refusal and STOP, cleanly, with a
    nonzero exit — a measuring instrument does not crash past its own gate
    (round 3)."""
    import tempfile
    with _draft() as art:
        if not sv.runtime_supported():
            print(f"unsupported-sqlite: {sqlite3.sqlite_version} has no "
                  f"qualified schema-runtime record in the draft evidence.")
            print("Regenerate in a disposable copy: "
                  "python3 specs/migrations_0013.py --write-evidence")
            return 2
        if not migration_runtime_supported(art):
            print(f"unsupported-sqlite: {sqlite3.sqlite_version} has no "
                  f"migration-confinement qualification.")
            print("Regenerate in a disposable copy: "
                  "python3 specs/migrations_0013.py --write-evidence")
            return 2

    p = tempfile.mktemp(suffix=".db")
    c = sqlite3.connect(p)
    for o in SCHEMA_V1:
        c.execute(o.ddl)
    for i in range(4):
        c.execute("INSERT INTO edges(id,user_id,subject,relation,object,active,"
                  "quarantined,json) VALUES(?,?,?,?,?,1,0,'{}')",
                  (f"e{i}", "u", f"s{i}", "r", "o"))
    c.execute("PRAGMA user_version = 1")
    c.commit()
    c.close()

    print(f"ordinary open on v1: {open_or_migrate(p)}")
    print(f"with authority:      {migrate_store(p, make_authority(p))}")
    print(f"reopen:              {open_or_migrate(p)}")

    c = sqlite3.connect(p)
    rows = c.execute("SELECT COUNT(*) FROM edges").fetchone()[0]
    print(f"edges preserved: {rows}/4")

    same = identity(manifest(c)) == _v2_constructor_objects()
    print(f"migration output byte-identical to constructor: {same}")

    # 0008 §6c semantics, demonstrated in the migrated schema. An omitted
    # correlation id is GENERATED by the library (round 2 corrected v2's NULL
    # model), so distinct generated ids coexist and a reused pair conflicts.
    c.execute("INSERT INTO confirmations VALUES('c1','u','e0','t','user',"
              "'host_api','gen-a','d1')")
    c.execute("INSERT INTO confirmations VALUES('c2','u','e1','t','user',"
              "'host_api','gen-b','d2')")
    try:
        c.execute("INSERT INTO confirmations VALUES('c3','u','e2','t','user',"
                  "'host_api','gen-a','d3')")
        dup = "ACCEPTED (wrong)"
    except sqlite3.IntegrityError:
        dup = "rejected (correct)"
    try:
        c.execute("INSERT INTO confirmations VALUES('c4','u','e3','t','user',"
                  "'host_api',NULL,'d4')")
        nulls = "ACCEPTED (wrong)"
    except sqlite3.IntegrityError:
        nulls = "rejected (correct)"
    print(f"generated ids coexist; duplicate (user, correlation): {dup}; "
          f"NULL correlation: {nulls}")
    return 0 if same and rows == 4 else 1


if __name__ == "__main__":
    if "--simulate" in sys.argv:
        raise SystemExit(simulate())
    if "--write-evidence" in sys.argv:
        raise SystemExit(write_evidence())
    if "--check-evidence" in sys.argv:
        raise SystemExit(check_evidence())
    print(__doc__)
