#!/usr/bin/env python3
"""Index the review archives in specs/archives/, and enforce their naming.

Naming convention:

    NNNN-v<version>-<YYYYMMDDTHHMMZ>.tar.gz
    0002-v7-20260802T0410Z.tar.gz

Spec number first so archives sort and group by spec; version so the archive is
tied to the document it carried; UTC timestamp so two archives of one version
are distinguishable and the ordering is unambiguous across sessions.

**The index is committed; the tarballs are not.** Each archive is a snapshot of
a tree that is already in git, so committing it stores the repo inside itself --
undiffable, unprunable, ~400KB per review round against a 93KiB packed history.
The sha256 recorded here is *stronger* provenance than an uncommitted binary:
it is tamper-evident, and anyone holding a copy can verify it is the one that
was sent.

If that trade is wrong, committing them later is one line in .gitignore.
Un-committing them is not.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARCHIVES = ROOT / "specs" / "archives"
INDEX = ARCHIVES / "INDEX.md"
NAME = re.compile(r"^(\d{4})-v(\d+)-(\d{8}T\d{4}Z)\.tar\.gz$")


def _entries():
    out, bad = [], []
    for f in sorted(ARCHIVES.glob("*.tar.gz")):
        m = NAME.match(f.name)
        if not m:
            bad.append(f.name)
            continue
        spec, ver, ts = m.groups()
        digest = hashlib.sha256(f.read_bytes()).hexdigest()
        n = len(subprocess.run(["tar", "tzf", str(f)], capture_output=True,
                               text=True).stdout.split())
        out.append(dict(name=f.name, spec=spec, ver=int(ver), ts=ts,
                        kb=round(f.stat().st_size / 1024), sha=digest, files=n))
    return out, bad


def render() -> str:
    entries, bad = _entries()
    if bad:
        raise SystemExit(
            "archive names do not match the convention "
            "`NNNN-v<version>-<YYYYMMDDTHHMMZ>.tar.gz`:\n  " + "\n  ".join(bad))
    rows = "\n".join(
        f"| `{e['name']}` | {e['spec']} | v{e['ver']} | "
        f"{e['ts'][:4]}-{e['ts'][4:6]}-{e['ts'][6:8]} {e['ts'][9:11]}:{e['ts'][11:13]}Z | "
        f"{e['files']} | {e['kb']} KB | `{e['sha'][:16]}…` |"
        for e in sorted(entries, key=lambda e: (e["spec"], e["ver"])))
    total = sum(e["kb"] for e in entries)
    return f"""<!-- GENERATED by specs/render_archives.py — do not hand-edit.
     Regenerate: python3 specs/render_archives.py --write
     Verify:     python3 specs/render_archives.py --check -->

# Review archives

**{len(entries)} archives, {total} KB.** Each is the exact package sent for one
external review round.

**Naming:** `NNNN-v<version>-<YYYYMMDDTHHMMZ>.tar.gz` — spec number first so
archives group by spec, version so the archive is tied to the document it
carried, UTC timestamp so two archives of one version are distinguishable and
the ordering is unambiguous across sessions. **The name is machine-checked.**

**The tarballs are not committed; this index is.** Each archive snapshots a tree
already in git, so committing it stores the repo inside itself — undiffable,
unprunable, and roughly 400 KB per review round against a 93 KiB packed history.
**The `sha256` below is stronger provenance than an uncommitted binary:** it is
tamper-evident, and anyone holding a copy can prove it is the one that was sent.

| archive | spec | version | sent (UTC) | files | size | sha256 |
|---|---|---|---|---|---|---|
{rows}

**To verify a copy you were sent:**

```sh
sha256sum 0002-v7-20260802T0410Z.tar.gz
```

**These are snapshots, not sources.** The repo is the source of truth; where an
archive and the repo disagree, the repo wins — and the disagreement is itself
the finding.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    want = render()
    if a.write:
        INDEX.write_text(want)
        print(f"wrote {INDEX.relative_to(ROOT)}")
        return 0
    if a.check:
        if not INDEX.exists() or INDEX.read_text() != want:
            print(f"{INDEX.name} is stale — run render_archives.py --write",
                  file=sys.stderr)
            return 1
        print("archive index is current and every name matches the convention")
        return 0
    print(want)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
