"""Phrases that have been withdrawn, and must not reappear in a spec.

Four external reviews in a row found withdrawn rules still stated normatively,
each time after the document claimed they had been removed. The failure was
always the same shape: I searched for *my own edits* -- annotation markers, the
sections I remembered touching -- rather than for every place the rule is
stated. A search for one's own corrections cannot find text one never annotated.

So the retraction list is now executable. Each entry is (rule_id, pattern,
reason, where-the-current-rule-lives). The rule_id is STABLE and load-bearing:
tests/test_withdrawn_gate_bites.py maps every motivating fixture to a specific
rule_id and asserts THAT entry matches it (R8-5 — proving a fixture matches
*any* entry lets a broad neighbour mask a dead one).
"""

WITHDRAWN = [
    # ---- 0014 (rounds 4-8): rules retired during the external review, restated
    # affirmatively nowhere. Underscores are stripped by _normalise (emphasis
    # folding), so identifiers are written normalised. Added at R6-6, which
    # correctly found the previous 'mechanized sweep' was an uncommitted script:
    # THIS list is the mechanism — committed, in the package, run by the suite.
    ("0014-payload-empty-legal",
     r"payload MAY be \{\}|\{\} (is|remains) (the )?legal|\{\} (only|remains .{0,20}legal) at|legal (form )?(ONLY )?at absorption.{0,3}s no.transfer",
     "R4-1/v8-0014: payloads are TOTAL at every site; {} is an integrity error",
     "specs/0014 §4a"),
    ("0014-empty-consumption",
     r"empty.payload consumption|no.payload consumption|payload empty or not|payload MAY be empty",
     "v8-0014: the consult-and-discard record is TOTAL; emptiness was retired with the base+contributor shape",
     "specs/0014 §4/A1/A7"),
    ("0014-legitimately-empty",
     r"which may legitimately be empty",
     "v8-0014: the total base+contributor/input shapes retired the empty payload",
     "specs/0014 §4"),
    ("0014-no-transfer-form",
     r"no.transfer form",
     "v8-0014: the no-transfer case is visible IN the recorded values",
     "specs/0014 §4a/A1"),
    ("0014-empty-payload-evasion",
     r"evasion is the empty payload|empty.payload evasion",
     "R8-5/0014: payloads are store-derived and total, and an empty payload aborts; the cheapest evasion is the NO-TRANSFER CONSUMPTION",
     "specs/0014 §1/§8"),
    ("0014-direct-restoration",
     r"direct restoration( material)?",
     "R4-1/0014: multi-prior absorption killed direct restoration; reversal is recomputation",
     "specs/0014 §7 Reversibility"),
    ("0014-no-format-bump",
     r"no FORMATVERSION change",
     "R5-4/0014: the exported Episode field bumps FORMAT_VERSION 4->5 (0010 refuse-dont-drop)",
     "specs/0014 §7a portability"),
    ("0014-sql-column",
     r"consolidationoutputindex INTEGER|episodes\.consolidationoutputindex",
     "R5-3/0014: the SQL-column form is withdrawn; the index is an Episode model field in the json blob",
     "specs/0014 §4c"),
    ("0014-preimage-into-request-digest",
     r"(pre.image|drafts?|contributions?) (ENTERS?|enters?) .{0,25}logicalrequestdigest",
     "R5-2/0014: the receipt split; the pre-image enters the OUTCOME digest, replay identity is the REQUEST digest",
     "specs/0014 §4b/§7b"),
    ("0014-loser-may-conflict",
     r"replays.or.conflicts per its receipt|the other replays or conflicts",
     "R8-1/0014: phase 2 is REQUEST-FIRST; a matching raw_request REPLAYS — the concurrent-preflight loser never conflicts",
     "specs/0014 §4b phase 2"),
    ("0014-no-ddl-beyond-ledger",
     r"no schema DDL beyond (the )?ledger",
     "R9-6/0014: the migration ALSO carries the receipts ALTERs; the Episode field adds no DDL of its own but the claim as stated contradicted §7a",
     "specs/0014 §4c/§7a"),
    ("0014-needs-confirmation-recomputed",
     r"needsconfirmation \(never cleared",
     "R9-4/0014: needs_confirmation is EXACT-EQUAL — the shipped absorption (graph.py:163-167) inherits only valid_from/observed_at/confidence and never touches it",
     "specs/0014 §4b partition"),
    ("0014-liveness-trust-transfers",
     r"liveness.trust transfers",
     "R9-4/0014: nothing beyond the C' three transfers at absorption; the vague transfer list misled the field partition",
     "specs/0014 §4b pre-image"),
    ("0014-replay-exact-persisted",
     r"returns EXACTLY the deserialized persisted response|replay equals O1 exactly",
     "R10-1/0014: the receipt persists the EFFECT payload (minus the runtime replayed flag); replay = effects + replayed=True — exact-copy replay contradicted the shipped runtime contract",
     "specs/0014 §4b R9-1 block"),
    ("0014-record-identical-reimport",
     r"accepted IFF it is RECORD.IDENTICAL",
     "R10-5/0014: the shipped remap mints fresh destination ids, so raw record equality never holds; re-import idempotency is SOURCE-IDENTICAL over normalized identity",
     "specs/0014 §2c output-index row"),
    ("0014-references-removed",
     r"REMAPPED fields REMOVED — exactly|every remapped REFERENCE field \(",
     "R12-3/R13-2/0014: reference fields are COMPARED (lineage/operation ids are stable historical per 0010 X18/X19 — compared verbatim, never removed, never remap-inverted)",
     "specs/0014 §2c output-index row (two-set projection)"),
    ("0014-lineage-remap-inversion",
     r"normalized BACK to the source.file id via the import.s remap table|destination lineage IDs? are inverted",
     "R13-2/0014: no such remap exists — the importer never remaps lineage (portability.py:279-291); historical ids are stable (0010 X18/X19) and compare verbatim",
     "specs/0014 §2c output-index row (two-set projection)"),
    ("0014-migrated-digest-identical",
     r"v6 store and a migrated v5 store are digest.identical|file imported twice.{0,60}(accepted as a )?no.op|whole.file.{0,30}no.op",
     "R11-1/R11-2/0014: fresh-constructor and ALTER-path DDL legitimately differ — MANIFESTS[6] is 0013 §4e's SET; and the re-import no-op is scoped to the indexed output, ordinary records keep shipped remap-copy semantics",
     "specs/0014 §4b R10-3 block / §2c output-index row"),
    ("0012-reinforcement-never-persists",
     r"reinforcement (never persists|does not persist) (the |its )?incoming",
     "0012 Design 1 LANDED: restatements persist as their own edges",
     "specs/0012 §4a; specs/0014 §1 historical note"),
    ("0014-validfrom-consolidation",
     r"validfrom\? (disclosure|derivedfrom)|validfrom is (in|part of) the consolidation",
     "R4-6/0014: Episodes have no valid_from; the consolidation set excludes it",
     "specs/0014 §4a"),
    # Narrowed deliberately. A first attempt matched any *description* of the
    # withdrawn rule -- "the generator added whatever a migration produced" --
    # which every review disposition and test docstring has to contain. A
    # pattern that forces a WITHDRAWN marker onto a dozen paragraphs stops being
    # a lint and becomes noise, and noisy lints get bypassed. These match an
    # affirmative restatement only. The real guard for the migration rule is
    # S50, which is executable.
    ("0007-both-runtimes-qualified",
     r"(3\.45\.1 and 3\.46\.1|3\.46\.1 and 3\.45\.1) (are|is|have been) (qualified|supported|recorded)",
     "R6/0007: the artifact records only 3.45.1; the package failed its own test on 3.46.1",
     "specs/0007 §4a-viii"),
    ("0007-txn-control-unreachable",
     r"transaction control .{0,30}(is|are) (not reachable|unreachable)|enforced by construction",
     "R5/0007: name mangling is not access control; migrations are declarative, and the claim is withdrawn",
     "specs/0007 §4d"),
    # `_normalise` strips underscores, so an identifier must be written
    # against the NORMALISED text: `LEGACY_DIGESTS` arrives as `LEGACYDIGESTS`.
    # This is the second time a pattern was written against raw markdown and
    # could never fire; a dead entry reads as coverage.
    ("0007-legacy-digests-map",
     r"LEGACY_?DIGESTS",
     "R5/0007: a digest->version map is the circular design; LEGACY_BASE_VERSIONS restricts resolution",
     "specs/0007 §4-i"),
    ("0007-tested-sqlite-tuple",
     r"TESTED_?SQLITE|the tested set is the contract",
     "R5/0007: a hand-edited tuple is not evidence; qualification is derived from sqlite_runtimes.json",
     "specs/0007 §4a-viii"),
    ("0007-declared-range",
     r"3\.35 ?<= ?sqlite|declares? (the )?(supported )?range",
     "R4/0007: a declared range with no evidence or enforcement is not a contract; gate on TESTED_SQLITE",
     "specs/0007 §4a-viii"),
    ("0007-immutable-entries",
     r"old entries .{0,20}are immutable(?!,? and now actually)|regenerates only the current constructor entry",
     "R4/0007: v5 said so and rewrote them; regenerating a historical version differently is now an error",
     "specs/0007 §4a-iv"),
    ("0007-whitespace-collapsed-ddl",
     r'" ?"\.join\(sql\.split\(\)\)|whitespace[- ]collapsed DDL|canonicalisation is deliberately minimal',
     "R3/0007: collapsing whitespace rewrites quoted literals; keep sqlite_master.sql byte-for-byte",
     "specs/0007 §4a"),
    ("0007-rebuildable-by-name",
     r"REBUILDABLE = \(|excluded from the digest by name",
     "R3/0007: identity is (type, name); a same-named trigger digested as clean",
     "specs/0007 §4a-0"),
    ("0007-one-manifest-per-version",
     r"one manifest per version|MANIFESTS: dict\[int, Manifest\]",
     "R3/0007: a version accepts a SET; a correct ALTER migration produces a different digest",
     "specs/0007 §4a-v"),
    ("0007-semantic-signature-bound",
     r"a semantic signature (bounds|is the strictest)|(indexes|indices) are (a )?performance only",
     "R2/0007: four more counterexamples passed it; the bound is known-constructor equality",
     "specs/0007 §4a"),
    ("0007-atomic-adoption-audit",
     r"adoption and (the )?audit are atomic|sink .{0,30}makes .{0,20}atomic",
     "R2/0007: a Python callback is outside the sqlite transaction; attempted/committed instead",
     "specs/0007 §4e"),
    ("0007-refuses-unknown-store",
     r"a veracium build refuses to open a store it does not understand",
     "R2/0007: false of all 23 released builds; the claim covers version-aware builds only",
     "specs/0007 §8"),
    ("0007-names-columns-strictest",
     r"names ?\+ ?columns.{0,40}strictest|names and declared types.{0,30}(strictest|sufficient)",
     "R1/0007: the reviewer built a constraint-stripped counterexample that matched",
     "specs/0007 §4a"),
    ("0007-indexes-performance-only",
     r"(indexes|indices) are a performance property",
     "R1/0007: a UNIQUE index decides which writes are accepted",
     "specs/0007 §4a-iii"),
    ("0007-create-index-restores",
     r"CREATE INDEX IF NOT EXISTS.{0,40}restores",
     "R1/0007: measured -- a wrong same-named index survives untouched",
     "specs/0007 §4a-iii"),
    # `_normalise` strips underscores and backticks before matching, so the
    # pattern must describe the NORMALISED text: `sqlite\_%` arrives as
    # `sqlite\%`. Written against the raw form first, this regex matched
    # nothing at all -- a lint entry that cannot fire is worse than none,
    # because it reads as coverage.
    ("0007-not-like-sqlite",
     r"NOT LIKE 'sqlite\\?%'(?! *(does not|ESCAPE))",
     "R1/0007: backslash is not a LIKE escape without ESCAPE; use GLOB",
     "specs/0007 §4a-i"),
    ("0008-same-author-clears",
     r"clears only on (evidence from the )?(the )?same author",
     "R3: only confirm() clears needs_confirmation; no field value does",
     "specs/0008 §3"),
    ("0008-author-class-clears",
     r"same author class.{0,40}(clear|evidence)",
     "R3: author class is not source identity",
     "specs/0008 §1"),
    ("0009-authorship-note",
     r"retain prior authorship in a note",
     "the note is rebuilt on every upgrade and survives one hop",
     "specs/0009 §4"),
    ("0002-falls-back-to-now",
     r"falls back to now|fallback to now|keep their (pre-)?existing fallback",
     "malformed dates are rejected; absence is the only thing meaning now",
     "specs/0002 §7f"),
    ("0002-validfrom-min-exception",
     r"valid_from = min.{0,30}sole exception",
     "R1: N1 is absolute; min is construction of a new edge",
     "specs/0002 §7c"),
    ("0002-audit-every-op",
     r"an audit of every maintenance-time operation",
     "withdrawn in §1; the audit is scoped to the manifest",
     "specs/0002 §8"),
    ("0002-fixes-three-defects",
     r"fixes three provenance defects",
     "0.4.5 ATTEMPTED three; M3 and M4 do not hold",
     "specs/0002 §8"),
    ("0002-manifest-cannot-drift",
     r"derived from the manifest.{0,40}cannot drift",
     "the evidence-bearing column is hand-authored",
     "specs/0002 §6a"),
    ("0002-general-form-both",
     r"the general form of both advisories",
     "N7 is an end-to-end gate; N9 is the general form",
     "specs/0002 §6"),
    ("0002-five-findings-closed",
     r"all five findings.{0,20}are closed",
     "M3, M4 and consolidation are unimplemented",
     "specs/0002 §11"),
    ("0002-m1-m5-closed",
     r"M1.M5,? all closed",
     "M3, M4, N9b-lineage, N4-decay and X-crash are unimplemented",
     "specs/0002 §11 — generated"),
    ("0002-hardcoded-counts",
     r"(three|four) (rows are red|external reviews)",
     "counts are generated from specs/findings.py",
     "specs/0002 §11, §12"),
    ("0002-046-unreleased",
     r"0\.4\.6 \(unreleased",
     "0.4.6 and 0.4.7 are both published",
     "specs/0002 §11 — generated"),
    ("0003-refuse-correct-nonassertable",
     r"refuse `?correct\(\)`? on a non-assertable edge",
     "Q5 resolved the other way: a correction inherits the corrected edge's class",
     "specs/0003 Q5, §M7"),
    ("0003-ladder-inverted",
     r"assistant . third_party.{0,10}allow|assistant . user.{0,10}block",
     "inverted: the ladder gives assistant->user ALLOW and assistant->third_party BLOCK",
     "specs/0003 §3"),
    ("0003-one-guard-one-loop",
     r"one guard in one loop",
     "the change spans write, read and storage — specs/0003 §7a",
     "specs/0003 §7a"),
    ("0003-full-400-row",
     r"the full 400.row",
     "the product follows the SHIPPED enum; 400 assumed a class that does not exist",
     "specs/ladder.py"),
    # ---- 0015 (round 3): the R2-3/R2-5 withdrawn claims survived in four
    # unswept carriers (R3-3) — exactly this registry's founding failure shape.
    ("0015-cli-gains-counters",
     r"CLI (`?remember`? )?(output|returns?) (gains?|keeps?) (the )?(two|both)|CLI (operator|caller)( sees| and .{0,30}sees)? the (counts|counters|two int)",
     "R2-3/R3-3: CLI output is UNCHANGED — cli.py prints its fixed summary; the counters reach the host-API return only",
     "specs/0015 §2/§4"),
    ("0015-lock-failure-blanket-false",
     r"acquisition failure( or timeout)? .{0,10}(the )?flush returns\s*.False.\s*and sends nothing",
     "R7-1/R8: the failure classes are SPLIT — pre-authorization returns False; a post-send failure returns True with last_sent unwritten; consolidated §4.5",
     "specs/0015 §4 rule 5 / I17"),
    ("0015-unix-only-lock",
     r"fcntl\.flock.{0,15}on\s*.telemetry\.json\.lock|the lock primitive,? pinned:?\s*.?fcntl",
     "R6-3/R8-1: the lock is the OS-exclusive adapter pair (flock/msvcrt.locking), one kernel contract — never a pinned Unix-only primitive nor a breakable lockfile",
     "specs/0015 §4 rule 2"),
    ("0015-nonnegative-epoch",
     r"consent.epoch.{0,40}non.negative|non.negative .{0,15}(int|integer).{0,40}epoch",
     "R7-4: the epoch validity predicate is POSITIVE int (bool excluded); zero is invalid; no live collector holds 0",
     "specs/0015 §4 rule 1 / I16"),
    ("0015-nothing-persisted",
     r"nothing persisted changes|(change|spec) persists nothing|nothing is persisted \(",
     "R2-5/R3-3: telemetry.json's schema_version (and consent_epoch) ARE persisted consent; claims are scoped to the MEMORY store",
     "specs/0015 §2/§4/§7"),
]
