"""Phrases that have been withdrawn, and must not reappear in a spec.

Four external reviews in a row found withdrawn rules still stated normatively,
each time after the document claimed they had been removed. The failure was
always the same shape: I searched for *my own edits* -- annotation markers, the
sections I remembered touching -- rather than for every place the rule is
stated. A search for one's own corrections cannot find text one never annotated.

So the retraction list is now executable. Each entry is a phrase that was
retracted, the reason, and where the current rule lives.
"""

WITHDRAWN = [
    (r"a semantic signature (bounds|is the strictest)|(indexes|indices) are (a )?performance only",
     "R2/0007: four more counterexamples passed it; the bound is known-constructor equality",
     "specs/0007 §4a"),
    (r"adoption and (the )?audit are atomic|sink .{0,30}makes .{0,20}atomic",
     "R2/0007: a Python callback is outside the sqlite transaction; attempted/committed instead",
     "specs/0007 §4e"),
    (r"a veracium build refuses to open a store it does not understand",
     "R2/0007: false of all 23 released builds; the claim covers version-aware builds only",
     "specs/0007 §8"),
    (r"names ?\+ ?columns.{0,40}strictest|names and declared types.{0,30}(strictest|sufficient)",
     "R1/0007: the reviewer built a constraint-stripped counterexample that matched",
     "specs/0007 §4a"),
    (r"(indexes|indices) are a performance property",
     "R1/0007: a UNIQUE index decides which writes are accepted",
     "specs/0007 §4a-iii"),
    (r"CREATE INDEX IF NOT EXISTS.{0,40}restores",
     "R1/0007: measured -- a wrong same-named index survives untouched",
     "specs/0007 §4a-iii"),
    # `_normalise` strips underscores and backticks before matching, so the
    # pattern must describe the NORMALISED text: `sqlite\_%` arrives as
    # `sqlite\%`. Written against the raw form first, this regex matched
    # nothing at all -- a lint entry that cannot fire is worse than none,
    # because it reads as coverage.
    (r"NOT LIKE 'sqlite\\?%'(?! *(does not|ESCAPE))",
     "R1/0007: backslash is not a LIKE escape without ESCAPE; use GLOB",
     "specs/0007 §4a-i"),
    (r"clears only on (evidence from the )?(the )?same author",
     "R3: only confirm() clears needs_confirmation; no field value does",
     "specs/0008 §3"),
    (r"same author class.{0,40}(clear|evidence)",
     "R3: author class is not source identity",
     "specs/0008 §1"),
    (r"retain prior authorship in a note",
     "the note is rebuilt on every upgrade and survives one hop",
     "specs/0009 §4"),
    (r"falls back to now|fallback to now|keep their (pre-)?existing fallback",
     "malformed dates are rejected; absence is the only thing meaning now",
     "specs/0002 §7f"),
    (r"valid_from = min.{0,30}sole exception",
     "R1: N1 is absolute; min is construction of a new edge",
     "specs/0002 §7c"),
    (r"an audit of every maintenance-time operation",
     "withdrawn in §1; the audit is scoped to the manifest",
     "specs/0002 §8"),
    (r"fixes three provenance defects",
     "0.4.5 ATTEMPTED three; M3 and M4 do not hold",
     "specs/0002 §8"),
    (r"derived from the manifest.{0,40}cannot drift",
     "the evidence-bearing column is hand-authored",
     "specs/0002 §6a"),
    (r"the general form of both advisories",
     "N7 is an end-to-end gate; N9 is the general form",
     "specs/0002 §6"),
    (r"all five findings.{0,20}are closed",
     "M3, M4 and consolidation are unimplemented",
     "specs/0002 §11"),
    (r"M1.M5,? all closed",
     "M3, M4, N9b-lineage, N4-decay and X-crash are unimplemented",
     "specs/0002 §11 — generated"),
    (r"(three|four) (rows are red|external reviews)",
     "counts are generated from specs/findings.py",
     "specs/0002 §11, §12"),
    (r"0\.4\.6 \(unreleased",
     "0.4.6 and 0.4.7 are both published",
     "specs/0002 §11 — generated"),
    (r"refuse `?correct\(\)`? on a non-assertable edge",
     "Q5 resolved the other way: a correction inherits the corrected edge's class",
     "specs/0003 Q5, §M7"),
    (r"assistant . third_party.{0,10}allow|assistant . user.{0,10}block",
     "inverted: the ladder gives assistant->user ALLOW and assistant->third_party BLOCK",
     "specs/0003 §3"),
    (r"one guard in one loop",
     "the change spans write, read and storage — specs/0003 §7a",
     "specs/0003 §7a"),
    (r"the full 400.row",
     "the product follows the SHIPPED enum; 400 assumed a class that does not exist",
     "specs/ladder.py"),
]
